/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.55
 * Generated at: 2020-06-02 16:57:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import java.util.logging.Level;
import com.nimbusds.jwt.SignedJWT;
import com.nimbusds.jwt.ReadOnlyJWTClaimsSet;
import org.json.JSONObject;
import org.wso2.sample.identity.oauth2.OAuth2Constants;
import java.util.Properties;
import org.wso2.sample.identity.oauth2.SampleContextEventListener;
import org.wso2.sample.identity.oauth2.CommonUtils;
import java.util.logging.Logger;
import java.util.HashMap;
import java.util.Map;
import org.wso2.samples.claims.manager.ClaimManagerProxy;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.wso2.sample.identity.oauth2.CommonUtils");
    _jspx_imports_classes.add("java.util.Properties");
    _jspx_imports_classes.add("org.wso2.sample.identity.oauth2.OAuth2Constants");
    _jspx_imports_classes.add("java.util.HashMap");
    _jspx_imports_classes.add("com.nimbusds.jwt.ReadOnlyJWTClaimsSet");
    _jspx_imports_classes.add("java.util.logging.Logger");
    _jspx_imports_classes.add("com.nimbusds.jwt.SignedJWT");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("java.util.logging.Level");
    _jspx_imports_classes.add("org.wso2.sample.identity.oauth2.SampleContextEventListener");
    _jspx_imports_classes.add("org.json.JSONObject");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("org.wso2.samples.claims.manager.ClaimManagerProxy");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<!--\n");
      out.write("~   Copyright (c) 2018 WSO2 Inc. (http://wso2.com) All Rights Reserved.\n");
      out.write("~\n");
      out.write("~   Licensed under the Apache License, Version 2.0 (the \"License\");\n");
      out.write("~   you may not use this file except in compliance with the License.\n");
      out.write("~   You may obtain a copy of the License at\n");
      out.write("~\n");
      out.write("~        http://www.apache.org/licenses/LICENSE-2.0\n");
      out.write("~\n");
      out.write("~   Unless required by applicable law or agreed to in writing, software\n");
      out.write("~   distributed under the License is distributed on an \"AS IS\" BASIS,\n");
      out.write("~   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n");
      out.write("~   See the License for the specific language governing permissions and\n");
      out.write("~   limitations under the License.\n");
      out.write("-->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    final Logger logger = Logger.getLogger(getClass().getName());
    final HttpSession currentSession =  request.getSession(false);
    
    if (currentSession == null || currentSession.getAttribute("authenticated") == null) {
        // A direct access to home. Must redirect to index
        response.sendRedirect("index.jsp");
        return;
    }
    
    final Properties properties = SampleContextEventListener.getProperties();
    final String sessionState = (String) currentSession.getAttribute(OAuth2Constants.SESSION_STATE);
   
    final JSONObject requestObject = (JSONObject) currentSession.getAttribute("requestObject");
    final JSONObject responseObject = (JSONObject) currentSession.getAttribute("responseObject");
    
    final String idToken = (String) currentSession.getAttribute("idToken");
    
    String name = "";

    Map<String, Object> customClaimValueMap = new HashMap<>();
    Map<String, String> oidcClaimDisplayValueMap = new HashMap();

    if (idToken != null) {
        try {
            name = SignedJWT.parse(idToken).getJWTClaimsSet().getSubject();
            ReadOnlyJWTClaimsSet claimsSet = SignedJWT.parse(idToken).getJWTClaimsSet();

            ClaimManagerProxy claimManagerProxy = (ClaimManagerProxy) application.getAttribute("claimManagerProxyInstance");

            customClaimValueMap = claimsSet.getCustomClaims();
            
            oidcClaimDisplayValueMap =
                    claimManagerProxy.getOidcClaimDisplayNameMapping(new ArrayList<>(customClaimValueMap.keySet()));

        } catch (Exception e) {
            logger.log(Level.SEVERE, "Error when getting id_token details.", e);
        }
    }

      out.write("\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("    <meta name=\"description\" content=\"PICKUP MANAGER - Management Application\">\n");
      out.write("\n");
      out.write("    <title>PICKUP MANAGER</title>\n");
      out.write("\n");
      out.write("    <!-- Bootstrap Material Design CSS -->\n");
      out.write("    <link href=\"libs/bootstrap-material-design_4.0.0/css/bootstrap-material-design.min.css\" rel=\"stylesheet\">\n");
      out.write("    <!-- Font Awesome icons -->\n");
      out.write("    <link href=\"libs/fontawesome-5.2.0/css/fontawesome.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"libs/fontawesome-5.2.0/css/solid.min.css\" rel=\"stylesheet\">\n");
      out.write("    <!-- Golden Layout styles -->\n");
      out.write("    <link href=\"libs/goldenlayout/css/goldenlayout-base.css\" rel=\"stylesheet\">\n");
      out.write("    <!-- Highlight styles -->\n");
      out.write("    <link href=\"libs/highlight_9.12.0/styles/atelier-cave-light.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <!-- Custom styles -->\n");
      out.write("    <link href=\"css/spinner.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"css/custom.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"css/manager.css\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body class=\"app-home\">\n");
      out.write("\n");
      out.write("<div id=\"wrapper\" class=\"wrapper\"></div>\n");
      out.write("\n");
      out.write("<div id=\"actionContainer\">\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-dark app-navbar justify-content-between\">\n");
      out.write("        <a class=\"navbar-brand\" href=\"home.jsp\"><i class=\"fas fa-taxi\"></i> PICKUP MANAGER</a>\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNavDropdown\"\n");
      out.write("                aria-controls=\"navbarNavDropdown\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("        </button>\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarNavDropdown\">\n");
      out.write("            <ul class=\"navbar-nav flex-row ml-md-auto \">\n");
      out.write("                <li class=\"nav-item dropdown \">\n");
      out.write("                    <a class=\"nav-link dropdown-toggle user-dropdown\" href=\"#\" id=\"navbarDropdownMenuLink\"\n");
      out.write("                       data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n");
      out.write("                        <i class=\"fas fa-user-circle\"></i> <span>");
      out.print(name);
      out.write("</span></span>\n");
      out.write("                    </a>\n");
      out.write("                    <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink\">\n");
      out.write("                        <a class=\"dropdown-item\" href=\"#\" id=\"profile\">Profile</a>\n");
      out.write("                        <a class=\"dropdown-item\" href='");
      out.print(properties.getProperty("OIDC_LOGOUT_ENDPOINT"));
      out.write("?post_logout_redirect_uri=");
      out.print(properties.getProperty("post_logout_redirect_uri"));
      out.write("&id_token_hint=");
      out.print(idToken);
      out.write("&session_state=");
      out.print(sessionState);
      out.write("'>\n");
      out.write("                            Logout</a>\n");
      out.write("                    </div>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" id=\"toggleView\" href=\"#\" data-toggle=\"tooltip\" data-placement=\"bottom\" title=\"Console\">\n");
      out.write("                        <i class=\"fa fa-cogs\"></i>\n");
      out.write("                    </a>\n");
      out.write("                </li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write("    <main role=\"main\" class=\"main-content\">\n");
      out.write("        <div id=\"main-content\">\n");
      out.write("            <section class=\"jumbotron text-center\">\n");
      out.write("                <div class=\"container\">\n");
      out.write("                    <div class=\"jumbotron-heading\">PICKUP MANAGER</div>\n");
      out.write("                    <p class=\"lead text-muted\">Management Application</p>\n");
      out.write("                </div>\n");
      out.write("            </section>\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <section id=\"tabs\">\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col-md-12\">\n");
      out.write("                            <nav>\n");
      out.write("                                <div class=\"nav nav-tabs nav-fill\" id=\"nav-tab\" role=\"tablist\">\n");
      out.write("                                    <a class=\"nav-item nav-link active\" id=\"nav-overview-tab\" data-toggle=\"tab\"\n");
      out.write("                                       href=\"#nav-overview\" role=\"tab\" aria-controls=\"nav-overview\" aria-selected=\"true\">Overview</a>\n");
      out.write("                                    <a class=\"nav-item nav-link\" id=\"nav-drivers-tab\" data-toggle=\"tab\" href=\"#nav-drivers\"\n");
      out.write("                                       role=\"tab\" aria-controls=\"nav-drivers\" aria-selected=\"false\">Drivers</a>\n");
      out.write("                                    <a class=\"nav-item nav-link\" id=\"nav-vehicles-tab\" data-toggle=\"tab\" href=\"#nav-vehicles\"\n");
      out.write("                                       role=\"tab\" aria-controls=\"nav-vehicles\" aria-selected=\"false\">Vehicles</a>\n");
      out.write("                                    <a class=\"nav-item nav-link\" id=\"nav-passengers-tab\" data-toggle=\"tab\"\n");
      out.write("                                       href=\"#nav-passengers\"\n");
      out.write("                                       role=\"tab\" aria-controls=\"nav-passengers\" aria-selected=\"false\">Passengers</a>\n");
      out.write("                                </div>\n");
      out.write("                            </nav>\n");
      out.write("                            <div class=\"tab-content py-3 px-3 px-sm-0\" id=\"nav-tabContent\">\n");
      out.write("                                <div class=\"tab-pane fade show active\" id=\"nav-overview\" role=\"tabpanel\"\n");
      out.write("                                     aria-labelledby=\"nav-overview-tab\">\n");
      out.write("                                    <div class=\"row\">\n");
      out.write("                                        <div class=\"col-md-4 mb-5 mt-5 text-center\">\n");
      out.write("                                            <i class=\"fas fa-users fa-3x green-text\"></i>\n");
      out.write("                                            <h4 class=\"my-4 tab-title\">Drivers</h4>\n");
      out.write("                                            <h4 class=\"grey-text\">30</h4>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"col-md-4 mb-1 mt-5 text-center\">\n");
      out.write("                                            <i class=\"fa fa-car fa-3x green-text\"></i>\n");
      out.write("                                            <h4 class=\"my-4 tab-title\">Vehicles</h4>\n");
      out.write("                                            <h4 class=\"grey-text\">40</h4>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"col-md-4 mb-1 mt-5 text-center\">\n");
      out.write("                                            <i class=\"fa fa-users fa-3x green-text\"></i>\n");
      out.write("                                            <h4 class=\"my-4 tab-title\">Passengers</h4>\n");
      out.write("                                            <h4 class=\"grey-text\">250</h4>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"tab-pane fade\" id=\"nav-drivers\" role=\"tabpanel\" aria-labelledby=\"nav-drivers-tab\">\n");
      out.write("                                    <div class=\"table-responsive content-table\">\n");
      out.write("                                        <table class=\"table\">\n");
      out.write("                                            <thead>\n");
      out.write("                                            <tr>\n");
      out.write("                                                <th>Driver ID</th>\n");
      out.write("                                                <th>Name</th>\n");
      out.write("                                                <th>Age</th>\n");
      out.write("                                                <th>Registration date</th>\n");
      out.write("                                                <th>Salary</th>\n");
      out.write("                                                <th></th>\n");
      out.write("                                            </tr>\n");
      out.write("                                            </thead>\n");
      out.write("                                            <tbody>\n");
      out.write("                                            <tr>\n");
      out.write("                                                <td>D0072</td>\n");
      out.write("                                                <td>Tiger Nixon</td>\n");
      out.write("                                                <td>40</td>\n");
      out.write("                                                <td class=\"date-time\"></td>\n");
      out.write("                                                <td>$120,800</td>\n");
      out.write("                                                <td><a href=\"#\" data-toggle=\"modal\" data-target=\"#sampleModal\"><i\n");
      out.write("                                                        class=\"fas fa-trash-alt\"></i></a></td>\n");
      out.write("                                            </tr>\n");
      out.write("                                            <tr>\n");
      out.write("                                                <td>D0053</td>\n");
      out.write("                                                <td>Joshua Winters</td>\n");
      out.write("                                                <td>33</td>\n");
      out.write("                                                <td class=\"date-time\"></td>\n");
      out.write("                                                <td>$110,750</td>\n");
      out.write("                                                <td><a href=\"#\" data-toggle=\"modal\" data-target=\"#sampleModal\"><i\n");
      out.write("                                                        class=\"fas fa-trash-alt\"></i></a></td>\n");
      out.write("                                            </tr>\n");
      out.write("                                            <tr>\n");
      out.write("                                                <td>D0046</td>\n");
      out.write("                                                <td>Lucas Thiyago</td>\n");
      out.write("                                                <td>23</td>\n");
      out.write("                                                <td class=\"date-time\"></td>\n");
      out.write("                                                <td>$106,000</td>\n");
      out.write("                                                <td><a href=\"#\" data-toggle=\"modal\" data-target=\"#sampleModal\"><i\n");
      out.write("                                                        class=\"fas fa-trash-alt\"></i></a></td>\n");
      out.write("                                            </tr>\n");
      out.write("                                            <tr>\n");
      out.write("                                                <td>D0027</td>\n");
      out.write("                                                <td>Woo Jin</td>\n");
      out.write("                                                <td>22</td>\n");
      out.write("                                                <td class=\"date-time\"></td>\n");
      out.write("                                                <td>$113,060</td>\n");
      out.write("                                                <td><a href=\"#\" data-toggle=\"modal\" data-target=\"#sampleModal\"><i\n");
      out.write("                                                        class=\"fas fa-trash-alt\"></i></a></td>\n");
      out.write("                                            </tr>\n");
      out.write("                                            <tr>\n");
      out.write("                                                <td>D0013</td>\n");
      out.write("                                                <td>Airi Satou</td>\n");
      out.write("                                                <td>43</td>\n");
      out.write("                                                <td class=\"date-time\"></td>\n");
      out.write("                                                <td>$112,700</td>\n");
      out.write("                                                <td><a href=\"#\" data-toggle=\"modal\" data-target=\"#sampleModal\"><i\n");
      out.write("                                                        class=\"fas fa-trash-alt\"></i></a></td>\n");
      out.write("                                            </tr>\n");
      out.write("                                            <tr>\n");
      out.write("                                                <td>D0009</td>\n");
      out.write("                                                <td>Brielle Williamson</td>\n");
      out.write("                                                <td>34</td>\n");
      out.write("                                                <td class=\"date-time\"></td>\n");
      out.write("                                                <td>$107,000</td>\n");
      out.write("                                                <td><a href=\"#\" data-toggle=\"modal\" data-target=\"#sampleModal\"><i\n");
      out.write("                                                        class=\"fas fa-trash-alt\"></i></a></td>\n");
      out.write("                                            </tr>\n");
      out.write("                                            </tbody>\n");
      out.write("                                        </table>\n");
      out.write("                                    </div>\n");
      out.write("                                    <button type=\"button\" class=\"btn btn-outline-primary content-btn d-block mx-auto\"\n");
      out.write("                                            data-toggle=\"modal\" data-target=\"#sampleModal\">Add\n");
      out.write("                                    </button>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"tab-pane fade\" id=\"nav-vehicles\" role=\"tabpanel\" aria-labelledby=\"nav-contact-tab\">\n");
      out.write("                                    <div class=\"table-responsive content-table\">\n");
      out.write("                                        <table class=\"table\">\n");
      out.write("                                            <thead>\n");
      out.write("                                            <tr>\n");
      out.write("                                                <th>Vehicle No</th>\n");
      out.write("                                                <th>Owner</th>\n");
      out.write("                                                <th>Vehicle Type</th>\n");
      out.write("                                                <th>Registration date</th>\n");
      out.write("                                                <th></th>\n");
      out.write("                                            </tr>\n");
      out.write("                                            </thead>\n");
      out.write("                                            <tbody>\n");
      out.write("                                            <tr>\n");
      out.write("                                                <td>CAS 234</td>\n");
      out.write("                                                <td>Tiger Nixon</td>\n");
      out.write("                                                <td>Car</td>\n");
      out.write("                                                <td class=\"date-time\"></td>\n");
      out.write("                                                <td><a href=\"#\" data-toggle=\"modal\" data-target=\"#sampleModal\"><i\n");
      out.write("                                                        class=\"fas fa-trash-alt\"></i></a></td>\n");
      out.write("                                            </tr>\n");
      out.write("                                            <tr>\n");
      out.write("                                                <td>KNW 456</td>\n");
      out.write("                                                <td>Lucas Thiyago</td>\n");
      out.write("                                                <td>Van</td>\n");
      out.write("                                                <td class=\"date-time\"></td>\n");
      out.write("                                                <td><a href=\"#\" data-toggle=\"modal\" data-target=\"#sampleModal\"><i\n");
      out.write("                                                        class=\"fas fa-trash-alt\"></i></a></td>\n");
      out.write("                                            </tr>\n");
      out.write("                                            <tr>\n");
      out.write("                                                <td>JDQ 887</td>\n");
      out.write("                                                <td>Joshua Winters</td>\n");
      out.write("                                                <td>Car</td>\n");
      out.write("                                                <td class=\"date-time\"></td>\n");
      out.write("                                                <td><a href=\"#\" data-toggle=\"modal\" data-target=\"#sampleModal\"><i\n");
      out.write("                                                        class=\"fas fa-trash-alt\"></i></a></td>\n");
      out.write("                                            </tr>\n");
      out.write("                                            <tr>\n");
      out.write("                                                <td>HGY 423</td>\n");
      out.write("                                                <td>Woo Jin</td>\n");
      out.write("                                                <td>Car</td>\n");
      out.write("                                                <td class=\"date-time\"></td>\n");
      out.write("                                                <td><a href=\"#\" data-toggle=\"modal\" data-target=\"#sampleModal\"><i\n");
      out.write("                                                        class=\"fas fa-trash-alt\"></i></a></td>\n");
      out.write("                                            </tr>\n");
      out.write("                                            <tr>\n");
      out.write("                                                <td>DBL 090</td>\n");
      out.write("                                                <td>Airi Satou</td>\n");
      out.write("                                                <td>Car</td>\n");
      out.write("                                                <td class=\"date-time\"></td>\n");
      out.write("                                                <td><a href=\"#\" data-toggle=\"modal\" data-target=\"#sampleModal\"><i\n");
      out.write("                                                        class=\"fas fa-trash-alt\"></i></a></td>\n");
      out.write("                                            </tr>\n");
      out.write("                                            <tr>\n");
      out.write("                                                <td>SAH 5555</td>\n");
      out.write("                                                <td>Brielle Williamson</td>\n");
      out.write("                                                <td>Van</td>\n");
      out.write("                                                <td class=\"date-time\"></td>\n");
      out.write("                                                <td><a href=\"#\" data-toggle=\"modal\" data-target=\"#sampleModal\"><i\n");
      out.write("                                                        class=\"fas fa-trash-alt\"></i></a></td>\n");
      out.write("                                            </tr>\n");
      out.write("                                            </tbody>\n");
      out.write("                                        </table>\n");
      out.write("                                    </div>\n");
      out.write("                                    <button type=\"button\" class=\"btn btn-outline-primary content-btn d-block mx-auto\"\n");
      out.write("                                            data-toggle=\"modal\" data-target=\"#sampleModal\">Add\n");
      out.write("                                    </button>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"tab-pane fade\" id=\"nav-passengers\" role=\"tabpanel\"\n");
      out.write("                                     aria-labelledby=\"nav-passengers-tab\">\n");
      out.write("                                    <div class=\"table-responsive content-table\">\n");
      out.write("                                        <table class=\"table\">\n");
      out.write("                                            <thead>\n");
      out.write("                                            <tr>\n");
      out.write("                                                <th>Passenger ID</th>\n");
      out.write("                                                <th>Name</th>\n");
      out.write("                                                <th>Registration Date</th>\n");
      out.write("                                                <th>No of Trips</th>\n");
      out.write("                                            </tr>\n");
      out.write("                                            </thead>\n");
      out.write("                                            <tbody>\n");
      out.write("                                            <tr>\n");
      out.write("                                                <td>P0064</td>\n");
      out.write("                                                <td>James Easton</td>\n");
      out.write("                                                <td class=\"date-time\"></td>\n");
      out.write("                                                <td>03</td>\n");
      out.write("                                            </tr>\n");
      out.write("                                            <tr>\n");
      out.write("                                                <td>P0052</td>\n");
      out.write("                                                <td>Ryan Martin</td>\n");
      out.write("                                                <td class=\"date-time\"></td>\n");
      out.write("                                                <td>10</td>\n");
      out.write("                                            </tr>\n");
      out.write("                                            <tr>\n");
      out.write("                                                <td>P0048</td>\n");
      out.write("                                                <td>Zofia Cox</td>\n");
      out.write("                                                <td class=\"date-time\"></td>\n");
      out.write("                                                <td>08</td>\n");
      out.write("                                            </tr>\n");
      out.write("                                            <tr>\n");
      out.write("                                                <td>P0037</td>\n");
      out.write("                                                <td>Kelly Carter</td>\n");
      out.write("                                                <td class=\"date-time\"></td>\n");
      out.write("                                                <td>03</td>\n");
      out.write("                                            </tr>\n");
      out.write("                                            <tr>\n");
      out.write("                                                <td>P0022</td>\n");
      out.write("                                                <td>Xing Wu</td>\n");
      out.write("                                                <td class=\"date-time\"></td>\n");
      out.write("                                                <td>15</td>\n");
      out.write("                                            </tr>\n");
      out.write("                                            <tr>\n");
      out.write("                                                <td>P0015</td>\n");
      out.write("                                                <td>Mariana Davis</td>\n");
      out.write("                                                <td class=\"date-time\"></td>\n");
      out.write("                                                <td>21</td>\n");
      out.write("                                            </tr>\n");
      out.write("                                            </tbody>\n");
      out.write("                                        </table>\n");
      out.write("                                    </div>\n");
      out.write("                                    <button type=\"button\" class=\"btn btn-outline-primary content-btn d-block mx-auto\"\n");
      out.write("                                            data-toggle=\"modal\" data-target=\"#sampleModal\">Add\n");
      out.write("                                    </button>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </section>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div id=\"profile-content\">\n");
      out.write("            <section class=\"jumbotron text-center\">\n");
      out.write("                <div class=\"container\">\n");
      out.write("                    <div class=\"user-icon\">\n");
      out.write("                        <i class=\"fas fa-user-circle fa-5x\"></i>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"jumbotron-heading\">");
      out.print(name);
      out.write("</div>\n");
      out.write("                </div>\n");
      out.write("            </section>\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-md-6 d-block mx-auto\">\n");
      out.write("                        <div class=\"card card-body table-container\">\n");
      out.write("                            <div class=\"table-responsive content-table\">\n");
      out.write("                            ");
if (!oidcClaimDisplayValueMap.isEmpty()) { 
      out.write("\n");
      out.write("                                <table class=\"table\">\n");
      out.write("                                    <thead>\n");
      out.write("                                    <tr>\n");
      out.write("                                        <th rowspan=\"2\">User Details</th>\n");
      out.write("                                    </tr>\n");
      out.write("                                    </thead>\n");
      out.write("                                    <tbody>\n");
      out.write("                                        ");
 for(String claim:oidcClaimDisplayValueMap.keySet()) { 
      out.write("\n");
      out.write("                                            <tr>\n");
      out.write("                                                <td>");
      out.print(oidcClaimDisplayValueMap.get(claim));
      out.write(" </td>\n");
      out.write("                                                <td>");
      out.print(customClaimValueMap.get(claim).toString());
      out.write(" </td>\n");
      out.write("                                            </tr>\n");
      out.write("                                        ");
 } 
      out.write("\n");
      out.write("                                    </tbody>\n");
      out.write("                                </table>\n");
      out.write("                            ");
  } else { 
      out.write("\n");
      out.write("                                    <p align=\"center\">No user details Available. Configure SP Claim Configurations.</p>\n");
      out.write("                            ");
  } 
      out.write("\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </main>\n");
      out.write("    <footer class=\"text-muted footer text-center\">\n");
      out.write("        <span>Copyright &copy;  <a href=\"http://wso2.com/\" target=\"_blank\">\n");
      out.write("            <img src=\"img/wso2-dark.svg\" class=\"wso2-logo\" alt=\"wso2-logo\"></a> &nbsp;<span class=\"year\"></span>\n");
      out.write("        </span>\n");
      out.write("    </footer>\n");
      out.write("\n");
      out.write("    <!-- sample application actions message -->\n");
      out.write("    <div class=\"modal fade\" id=\"sampleModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"basicModal\" aria-hidden=\"true\">\n");
      out.write("        <div class=\"modal-dialog\">\n");
      out.write("            <div class=\"modal-content\">\n");
      out.write("                <div class=\"modal-header\">\n");
      out.write("                    <h5 class=\"modal-title\" id=\"myModalLabel\">You cannot perform this action</h5>\n");
      out.write("                    <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("                        <span aria-hidden=\"true\">&times;</span>\n");
      out.write("                    </button>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"modal-body\">\n");
      out.write("                    <p>Sample application functionalities are added for display purposes only.</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"modal-footer\">\n");
      out.write("                    <button type=\"button\" class=\"btn btn-primary\" data-dismiss=\"modal\">OK</button>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("<div id=\"viewContainer\">\n");
      out.write("    <section class=\"actions\">\n");
      out.write("        <div class=\"container-fluid\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-md-12 console-headers\">\n");
      out.write("                    <span id=\"console-close\" class=\"float-right console-action\">\n");
      out.write("                        <span data-toggle=\"tooltip\" data-placement=\"bottom\" title=\"Close\"><i\n");
      out.write("                                class=\"fas fa-times\"></i></span>\n");
      out.write("                    </span>\n");
      out.write("                    <span id=\"toggleLayout\" class=\"float-right console-action\">\n");
      out.write("                        <span data-toggle=\"tooltip\" data-placement=\"bottom\" title=\"Dock to bottom\"><i\n");
      out.write("                                class=\"fas fa-window-maximize\"></i></span>\n");
      out.write("                    </span>\n");
      out.write("                    <span id=\"clearAll\" class=\"float-right console-action\">\n");
      out.write("                        <span data-toggle=\"tooltip\" data-placement=\"bottom\" title=\"Clear All\"><i class=\"fas fa-ban\"></i></span>\n");
      out.write("                    </span>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-12\">\n");
      out.write("                    <div id=\"timeline-content\">\n");
      out.write("                        <ul class=\"timeline\">\n");
      out.write("                            <li class=\"event sent\">\n");
      out.write("                                <div class=\"request-response-infos\">\n");
      out.write("                                    <h1 class='request-response-title'>Request <span class=\"float-right\"><i\n");
      out.write("                                            class=\"fas fa-angle-down\"></i></span></h1>\n");
      out.write("                                    <div class=\"request-response-details mt-3\">\n");
      out.write("                                        <h2>Data:</h2>\n");
      out.write("                                        <div class=\"code-container mb-3\">\n");
      out.write("                                            <button class=\"btn btn-primary btn-clipboard\"\n");
      out.write("                                                    data-clipboard-target=\".copy-target1\"><i\n");
      out.write("                                                    class=\"fa fa-clipboard\"></i></button>\n");
      out.write("                                            <p class=\"copied\">Copied..!</p>\n");
      out.write("                                            <pre><code class=\"copy-target1 JSON pt-3 pb-3\">");
      out.print(requestObject.toString(4));
      out.write("</code></pre>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <input type=\"hidden\" id=\"request\" value=\"");
      out.print(requestObject.toString());
      out.write("\"/>\n");
      out.write("                            </li>\n");
      out.write("                            <li class=\"event received\">\n");
      out.write("                                <div class=\"request-response-infos\">\n");
      out.write("                                    <h1 class='request-response-title'>Response <span class=\"float-right\"><i\n");
      out.write("                                            class=\"fa fa-angle-down\"></i></span></h1>\n");
      out.write("                                    <div class=\"request-response-details mt-3\">\n");
      out.write("                                        <h2>Data:</h2>\n");
      out.write("                                        <div class=\"code-container mb-3\">\n");
      out.write("                                            <button class=\"btn btn-primary btn-clipboard\"\n");
      out.write("                                                    data-clipboard-target=\".copy-target3\"><i\n");
      out.write("                                                    class=\"fa fa-clipboard\"></i></button>\n");
      out.write("                                            <p class=\"copied\">Copied..!</p>\n");
      out.write("                                            <pre><code class=\"copy-target3 JSON pt-3 pb-3 requestContent\">");
      out.print(responseObject.toString(4));
      out.write("</code></pre>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </li>\n");
      out.write("                        </ul>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- JQuery -->\n");
      out.write("<script src=\"libs/jquery_3.3.1/jquery.min.js\"></script>\n");
      out.write("<!-- Popper -->\n");
      out.write("<script src=\"libs/popper_1.12.9/popper.min.js\"></script>\n");
      out.write("<!-- Bootstrap Material Design JavaScript -->\n");
      out.write("<script src=\"libs/bootstrap-material-design_4.0.0/js/bootstrap-material-design.min.js\"></script>\n");
      out.write("<!-- Moment -->\n");
      out.write("<script src=\"libs/moment_2.11.2/moment.min.js\"></script>\n");
      out.write("<!-- Golden Layout -->\n");
      out.write("<script src=\"libs/goldenlayout/js/goldenlayout.min.js\"></script>\n");
      out.write("<!-- Highlight -->\n");
      out.write("<script src=\"libs/highlight_9.12.0/highlight.pack.js\"></script>\n");
      out.write("<!-- Clipboard -->\n");
      out.write("<script src=\"libs/clipboard/clipboard.min.js\"></script>\n");
      out.write("<!-- Custom Js -->\n");
      out.write("<script src=\"js/custom.js\"></script>\n");
      out.write("<iframe id=\"rpIFrame\" src=\"rpIFrame.jsp\" frameborder=\"0\" width=\"0\" height=\"0\"></iframe>\n");
      out.write("<script>hljs.initHighlightingOnLoad();</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
